name: Release Versioning

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - name: Release please action
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      
      - name: echoing
        run: |
          echo " release create --> ${{ steps.release.outputs.releases_created }} "
          echo "release number -->  ${{ fromJSON(steps.release.outputs.pr).number }} "

      - name: Checkout repository
        if: ${{ !steps.release.outputs.releases_created }}
        uses: actions/checkout@v3

      - name: "Merge pull request"
        if: ${{ !steps.release.outputs.releases_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: gh pr merge -s ${{ fromJSON(steps.release.outputs.pr).number }} --admin